HOuse pricing porjext kaggle

In [257]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [258]:
train = pd.read_csv('train.csv')

In [259]:
test = pd.read_csv('test.csv')

In [260]:
train.select_dtypes(include='object').isnull().sum()[train.isnull().sum()>0].sort_values(ascending=False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
GarageFinish      81
GarageQual        81
GarageType        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtFinType1      37
BsmtCond          37
Electrical         1
dtype: int64

In [261]:
train.select_dtypes(include='number').isnull().sum()[train.isnull().sum()>0].sort_values(ascending=False)

LotFrontage    259
GarageYrBlt     81
MasVnrArea       8
dtype: int64

In [262]:
num_cols_missing = ['LotFrontage','GarageYrBlt','MasVnrArea']

In [263]:
train[num_cols_missing]=train[num_cols_missing].fillna(train[num_cols_missing].mean())

In [264]:
cat_cols_missiing = train.select_dtypes(include='object').columns

In [265]:
train[cat_cols_missiing] = train[cat_cols_missiing].fillna("None")

In [266]:
test.select_dtypes(include='object').isnull().sum()[test.isnull().sum()>0].sort_values(ascending=False)

PoolQC          1456
MiscFeature     1408
Alley           1352
Fence           1169
MasVnrType       894
FireplaceQu      730
GarageFinish      78
GarageQual        78
GarageCond        78
GarageType        76
BsmtCond          45
BsmtExposure      44
BsmtQual          44
BsmtFinType1      42
BsmtFinType2      42
MSZoning           4
Utilities          2
Functional         2
Exterior2nd        1
Exterior1st        1
KitchenQual        1
SaleType           1
dtype: int64

In [267]:
cat_cols_missiing_test = test.select_dtypes(include='object').columns

In [268]:
test.select_dtypes(include='number').isnull().sum()[test.isnull().sum()>0].sort_values(ascending=False)

LotFrontage     227
GarageYrBlt      78
MasVnrArea       15
BsmtHalfBath      2
BsmtFullBath      2
BsmtFinSF1        1
BsmtFinSF2        1
TotalBsmtSF       1
BsmtUnfSF         1
GarageCars        1
GarageArea        1
dtype: int64

In [269]:
num_cols_missing_test = test.select_dtypes(include='number').columns

In [270]:
test[num_cols_missing_test] = test[num_cols_missing_test].fillna(test[num_cols_missing_test].mean())

In [271]:
test[cat_cols_missiing_test] = test[cat_cols_missiing_test].fillna("None")

In [272]:
result = pd.DataFrame()

In [273]:
result['Id'] = test['Id']

In [274]:
train.drop('Id',axis=1,inplace=True)

In [275]:
test.drop('Id',axis=1,inplace=True)

In [276]:
train[cat_cols_missiing].nunique().sort_values()

Street            2
Utilities         2
CentralAir        2
LandSlope         3
Alley             3
PavedDrive        3
MasVnrType        4
LandContour       4
ExterQual         4
KitchenQual       4
GarageFinish      4
LotShape          4
PoolQC            4
BldgType          5
BsmtCond          5
BsmtExposure      5
HeatingQC         5
BsmtQual          5
MSZoning          5
MiscFeature       5
Fence             5
ExterCond         5
LotConfig         5
Electrical        6
GarageQual        6
GarageCond        6
FireplaceQu       6
Foundation        6
RoofStyle         6
Heating           6
SaleCondition     6
BsmtFinType1      7
BsmtFinType2      7
GarageType        7
Functional        7
HouseStyle        8
RoofMatl          8
Condition2        8
SaleType          9
Condition1        9
Exterior1st      15
Exterior2nd      16
Neighborhood     25
dtype: int64

In [277]:
binary_cols = train[cat_cols_missiing].nunique()[train[cat_cols_missiing].nunique()==2].index
binary_cols

Index(['Street', 'Utilities', 'CentralAir'], dtype='object')

In [278]:
cat_cols = train[cat_cols_missiing]
nunique = cat_cols.nunique()

In [279]:
low_card_cols = nunique[(nunique>=3) & (nunique <=10)].index

In [280]:
low_card_cols

Index(['MSZoning', 'Alley', 'LotShape', 'LandContour', 'LotConfig',
       'LandSlope', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'RoofStyle', 'RoofMatl', 'MasVnrType', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'Heating', 'HeatingQC', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [281]:
high_card_cols = nunique[nunique>10].index

In [282]:
high_card_cols

Index(['Neighborhood', 'Exterior1st', 'Exterior2nd'], dtype='object')

In [283]:
from sklearn.preprocessing import LabelEncoder

In [284]:
le = LabelEncoder()

In [285]:
for col in binary_cols:
    train[col] = le.fit_transform(train[col])

In [286]:
for col in binary_cols:
    test[col] = le.fit_transform(test[col])

In [287]:
train = pd.get_dummies(train,columns=low_card_cols.union(high_card_cols))

In [288]:
test = pd.get_dummies(test,columns=low_card_cols.union(high_card_cols))

In [289]:
train

,MSSubClass,LotFrontage,LotArea,Street,Utilities,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,SaleCondition_Partial,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD
0,60,65.0,8450,1,0,7,5,2003,2003,196.0,...,False,False,False,False,False,False,False,False,False,True
1,20,80.0,9600,1,0,6,8,1976,1976,0.0,...,False,False,False,False,False,False,False,False,False,True
2,60,68.0,11250,1,0,7,5,2001,2002,162.0,...,False,False,False,False,False,False,False,False,False,True
3,70,60.0,9550,1,0,7,5,1915,1970,0.0,...,False,False,False,False,False,False,False,False,False,True
4,60,84.0,14260,1,0,8,5,2000,2000,350.0,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,1,0,6,5,1999,2000,0.0,...,False,False,False,False,False,False,False,False,False,True
1456,20,85.0,13175,1,0,6,6,1978,1988,119.0,...,False,False,False,False,False,False,False,False,False,True
1457,70,66.0,9042,1,0,7,9,1941,2006,0.0,...,False,False,False,False,False,False,False,False,False,True
1458,20,68.0,9717,1,0,5,6,1950,1996,0.0,...,False,False,False,False,False,False,False,False,False,True
1459,20,75.0,9937,1,0,5,6,1965,1965,0.0,...,False,False,False,False,False,False,False,False,False,True

In [290]:
test

,MSSubClass,LotFrontage,LotArea,Street,Utilities,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD
0,20,80.0,11622,1,0,5,6,1961,1961,0.0,...,False,False,False,False,False,False,False,False,False,True
1,20,81.0,14267,1,0,6,6,1958,1958,108.0,...,False,False,False,False,False,False,False,False,False,True
2,60,74.0,13830,1,0,5,5,1997,1998,0.0,...,False,False,False,False,False,False,False,False,False,True
3,60,78.0,9978,1,0,6,6,1998,1998,20.0,...,False,False,False,False,False,False,False,False,False,True
4,120,43.0,5005,1,0,8,5,1992,1992,0.0,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21.0,1936,1,0,4,7,1970,1970,0.0,...,False,False,False,False,False,False,False,False,False,True
1455,160,21.0,1894,1,0,4,5,1970,1970,0.0,...,False,False,False,False,False,False,False,False,False,True
1456,20,160.0,20000,1,0,5,7,1960,1996,0.0,...,False,False,False,False,False,False,False,False,False,True
1457,85,62.0,10441,1,0,5,5,1992,1992,0.0,...,False,False,False,False,False,False,False,False,False,True
1458,60,74.0,9627,1,0,7,5,1993,1994,94.0,...,False,False,False,False,False,False,False,False,False,True

In [291]:
train.astype(int)

,MSSubClass,LotFrontage,LotArea,Street,Utilities,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,SaleCondition_Partial,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD
0,60,65,8450,1,0,7,5,2003,2003,196,...,0,0,0,0,0,0,0,0,0,1
1,20,80,9600,1,0,6,8,1976,1976,0,...,0,0,0,0,0,0,0,0,0,1
2,60,68,11250,1,0,7,5,2001,2002,162,...,0,0,0,0,0,0,0,0,0,1
3,70,60,9550,1,0,7,5,1915,1970,0,...,0,0,0,0,0,0,0,0,0,1
4,60,84,14260,1,0,8,5,2000,2000,350,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62,7917,1,0,6,5,1999,2000,0,...,0,0,0,0,0,0,0,0,0,1
1456,20,85,13175,1,0,6,6,1978,1988,119,...,0,0,0,0,0,0,0,0,0,1
1457,70,66,9042,1,0,7,9,1941,2006,0,...,0,0,0,0,0,0,0,0,0,1
1458,20,68,9717,1,0,5,6,1950,1996,0,...,0,0,0,0,0,0,0,0,0,1
1459,20,75,9937,1,0,5,6,1965,1965,0,...,0,0,0,0,0,0,0,0,0,1

In [292]:
test.astype(int)

,MSSubClass,LotFrontage,LotArea,Street,Utilities,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,...,SaleType_COD,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_None,SaleType_Oth,SaleType_WD
0,20,80,11622,1,0,5,6,1961,1961,0,...,0,0,0,0,0,0,0,0,0,1
1,20,81,14267,1,0,6,6,1958,1958,108,...,0,0,0,0,0,0,0,0,0,1
2,60,74,13830,1,0,5,5,1997,1998,0,...,0,0,0,0,0,0,0,0,0,1
3,60,78,9978,1,0,6,6,1998,1998,20,...,0,0,0,0,0,0,0,0,0,1
4,120,43,5005,1,0,8,5,1992,1992,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,160,21,1936,1,0,4,7,1970,1970,0,...,0,0,0,0,0,0,0,0,0,1
1455,160,21,1894,1,0,4,5,1970,1970,0,...,0,0,0,0,0,0,0,0,0,1
1456,20,160,20000,1,0,5,7,1960,1996,0,...,0,0,0,0,0,0,0,0,0,1
1457,85,62,10441,1,0,5,5,1992,1992,0,...,0,0,0,0,0,0,0,0,0,1
1458,60,74,9627,1,0,7,5,1993,1994,94,...,0,0,0,0,0,0,0,0,0,1

In [293]:
x = train.drop('SalePrice',axis = 1)

In [294]:
y = train['SalePrice']

In [295]:
x, test = x.align(test, join='left', axis=1, fill_value=0)

In [296]:
x.shape

(1460, 300)

In [297]:
test.shape

(1459, 300)

In [298]:
x.columns.equals(test.columns)

True

In [300]:
print(x.isnull().sum().sum())
print(test.isnull().sum().sum())

0
0

In [301]:
y = np.log1p(y)

0       12.247699
1       12.109016
2       12.317171
3       11.849405
4       12.429220
          ...
1455    12.072547
1456    12.254868
1457    12.493133
1458    11.864469
1459    11.901590
Name: SalePrice, Length: 1460, dtype: float64

Preprcessign done

## MOdel Trainign time

In [304]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

In [305]:
para_dist = {
    "n_estimators": [100,200,300,400,500],
    "max_depth" :[None,5,10,15,20,25],
    "min_samples_leaf":[2,4,6],
    "min_samples_split":[2,5,10],
    'max_features': ['sqrt', 'log2', None]
}
model = RandomForestRegressor()

In [306]:
rscv = RandomizedSearchCV(
    estimator=model,
    param_distributions=para_dist,
    n_iter=30,
    random_state=42,
    n_jobs=-1,
    cv=5,
    verbose=1
)

In [307]:
rscv.fit(x,y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_iter=30,
                   n_jobs=-1,
                   param_distributions={'max_depth': [None, 5, 10, 15, 20, 25],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [2, 4, 6],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500]},
                   random_state=42, verbose=1)

In [310]:
rscv.best_params_

{'n_estimators': 500,
 'min_samples_split': 2,
 'min_samples_leaf': 4,
 'max_features': None,
 'max_depth': None}

In [311]:
pred = rscv.predict(test)

In [ ]:
revLog_pred = np.expm1(pred)

In [317]:
result['SalePrice'] = revLog_pred

In [318]:
result

        Id      SalePrice
0     1461  125128.557136
1     1462  154307.935997
2     1463  179799.631545
3     1464  180488.594430
4     1465  195730.042154
...    ...            ...
1454  2915   82922.805831
1455  2916   85772.461569
1456  2917  151595.328825
1457  2918  114478.107577
1458  2919  231060.931761

[1459 rows x 2 columns]

In [319]:
result.to_csv("housing_submission.csv",index=False)